spotify
b00tc4mp/skylab-bootcamp-201807 pull request #80
Opened 2018-07-18 13:07 UTC by eduberenguer

2018-07-18 13:18 UTC, pausanchez commented on staff/edu-berenguer/spotify-app/scripts/main.js
> +// my custom components
missing 'use strict'

2018-07-18 13:18 UTC, pausanchez commented on staff/edu-berenguer/spotify-app/scripts/main.js
> +var DEFAULT_IMAGE = "https://www.google.es";
"https://www.google.es" is not an image url

2018-07-18 13:35 UTC, bcasasus commented on staff/edu-berenguer/spotify-app/scripts/logic.spec.js
>  'use strict';
well done using 'use strict'

2018-07-18 13:35 UTC, bcasasus commented on staff/edu-berenguer/restaurants-app/scripts/main.js
> +// my custom components
'use strict' required!!!!

2018-07-18 13:35 UTC, bcasasus commented on staff/edu-berenguer/restaurants-app/scripts/main.js
> +function ResultsList() {
maybe you could use `/***` to comment the function of the methods

2018-07-18 13:35 UTC, bcasasus commented on staff/edu-berenguer/restaurants-app/scripts/main.js
> +search2.onSearch(function (query) {
the name search2 is not semmantic, and the functionality is redundant

2018-07-23 07:38 UTC, bcasasus commented on staff/edu-berenguer/spotify-app/scripts/logic.js
>      _callApi: function (path) {
Maybe you could use `  _callApi: function (path) {
        return $.ajax('https://api.spotify.com/v1' + path, {
            headers: {
                authorization: 'Bearer ' + this.token
            }
        })
        .catch(function(err) {
            throw Error('request error, status ' + err.status);
        });
    }`

2018-07-23 07:40 UTC, pausanchez commented on staff/edu-berenguer/spotify-app/style.css
> +    background: linear-gradient(to right, #08EA90, #22d243); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
Estilo doble

2018-07-23 07:47 UTC, SergioCastilloSorribes requested changes

2018-07-23 07:47 UTC, SergioCastilloSorribes commented on staff/edu-berenguer/array-native/scripts/copy-with-in.test.js
> +        expect(result2).toEqual([1, 4, 5, 4, 5])
Falta semicolon!!!! Esto no es react!!!Tienes que mejorar!!!

2018-08-06 14:15 UTC, merged