Apps
b00tc4mp/skylab-bootcamp-201807 pull request #82
Opened 2018-07-18 13:08 UTC by sergisanrama

2018-07-18 13:24 UTC, ghost requested changes
Some changes.

2018-07-18 13:24 UTC, ghost commented on staff/sergi-sanrama/spotify-app/scripts/main.js
> +// my presentation logic
use strict

2018-07-18 13:24 UTC, ghost commented on staff/sergi-sanrama/spotify-app/scripts/main.js
> +            resultsArtists.updateResults(artists.map(function (artist) {
You should also include the artist's image (you could pass the array unchanged and the manage it later).

2018-07-18 13:24 UTC, ghost commented on staff/sergi-sanrama/spotify-app/scripts/main.js
> +            alert('Sorry, we have temporary problem, try again later.');
Maybe a more detailed message could be useful.

2018-07-18 13:24 UTC, ghost commented on staff/sergi-sanrama/spotify-app/scripts/main.js
> +            resultsAlbums.updateResults(albums.map(function (album) {
you should pass the entire array and manage it later (for example to retrieve the image).

2018-07-18 13:24 UTC, ghost commented on staff/sergi-sanrama/spotify-app/scripts/main.js
> +            alert('Sorry, we have temporary problem, try again later.');
A more detailed message could be useful.

2018-07-18 13:24 UTC, ghost commented on staff/sergi-sanrama/spotify-app/scripts/main.js
> +var resultsAlbums = new ResultsList();
You could overwrite the updateResults function in order to show more information (images and other text).

2018-07-18 13:29 UTC, gbaste commented on staff/sergi-sanrama/spotify-app/scripts/logic.js
>  var logic = {
Hi Sergi, you need add 'use strict' at the beginning of the js page

2018-07-18 13:33 UTC, gbaste commented on staff/sergi-sanrama/arrays/scripts/most-frequent.js
> +                numberArray.push(array[i])
Need put semicolons ;;;;;

2018-07-18 13:35 UTC, sergisanrama commented on staff/sergi-sanrama/spotify-app/scripts/logic.js
>  var logic = {
fixed

2018-07-18 13:35 UTC, sergisanrama commented on staff/sergi-sanrama/spotify-app/scripts/main.js
> +// my presentation logic
fixed

2018-07-23 07:45 UTC, sergisanrama commented on staff/sergi-sanrama/arrays/scripts/most-frequent.js
> +                numberArray.push(array[i])
fixed

2018-07-23 07:46 UTC, sergisanrama commented on staff/sergi-sanrama/spotify-app/scripts/main.js
> +            resultsArtists.updateResults(artists.map(function (artist) {
implemented

2018-07-23 07:46 UTC, sergisanrama commented on staff/sergi-sanrama/spotify-app/scripts/main.js
> +            resultsAlbums.updateResults(albums.map(function (album) {
ready

2018-08-07 07:37 UTC, merged